from dataclasses import dataclass


@dataclass(frozen=True)
class IndicatorMeta:
    code: str
    name: str
    category: str
    unit: str
    gold_table: str
    analytics_table: str | None = None
    description: str = ""
    aliases: tuple[str, ...] = ()


INDICATORS: dict[str, IndicatorMeta] = {
    
    # 1. Growth dynamics
    
    "rGDP_growth_YoY": IndicatorMeta(
        code="rGDP_growth_YoY",
        name="Real GDP Growth Year-over-Year",
        category="growth_dynamics",
        unit="%",
        gold_table="gold_growth_dynamics",
        analytics_table="analytics_gold_growth_dynamics",
        description="Tốc độ tăng trưởng GDP thực tế so với cùng kỳ năm trước.",
        aliases=(
            "real gdp growth",
            "real gdp growth yoy",
            "tăng trưởng gdp thực",
            "tang truong gdp thuc",
            "tăng trưởng kinh tế thực",
            "tang truong kinh te thuc",
            "gdp thực",
            "gdp thuc",
        ),
    ),
    "rolling_mean_5yr": IndicatorMeta(
        code="rolling_mean_5yr",
        name="5-Year Rolling Mean Growth",
        category="growth_dynamics",
        unit="%",
        gold_table="gold_growth_dynamics",
        analytics_table="analytics_gold_growth_dynamics",
        description="Trung bình trượt 5 năm của tăng trưởng GDP.",
        aliases=(
            "rolling mean 5 year",
            "rolling mean 5yr",
            "trung bình trượt 5 năm",
            "trung binh truot 5 nam",
            "xu hướng tăng trưởng 5 năm",
            "xu huong tang truong 5 nam",
        ),
    ),
    "trend_deviation": IndicatorMeta(
        code="trend_deviation",
        name="Trend Deviation",
        category="growth_dynamics",
        unit="%",
        gold_table="gold_growth_dynamics",
        analytics_table="analytics_gold_growth_dynamics",
        description="Độ lệch tăng trưởng thực tế so với xu hướng dài hạn.",
        aliases=(
            "trend deviation",
            "độ lệch xu hướng",
            "do lech xu huong",
            "lệch xu hướng",
            "lech xu huong",
            "điểm gãy cấu trúc",
            "diem gay cau truc",
        ),
    ),
    "GDP_growth_YoY": IndicatorMeta(
        code="GDP_growth_YoY",
        name="Nominal GDP Growth Year-over-Year",
        category="growth_dynamics",
        unit="%",
        gold_table="gold_growth_dynamics",
        analytics_table="analytics_gold_growth_dynamics",
        description="Tăng trưởng GDP danh nghĩa.",
        aliases=(
            "nominal gdp growth",
            "gdp growth yoy",
            "tăng trưởng gdp danh nghĩa",
            "tang truong gdp danh nghia",
            "tăng trưởng gdp",
            "tang truong gdp",
        ),
    ),
    "GDP_growth_trend_5yr": IndicatorMeta(
        code="GDP_growth_trend_5yr",
        name="GDP Growth Trend 5-year",
        category="growth_dynamics",
        unit="%",
        gold_table="gold_growth_dynamics",
        analytics_table=None,
        description="Xu hướng tăng trưởng GDP trong 5 năm.",
        aliases=(
            "gdp growth trend 5 year",
            "gdp growth trend 5yr",
            "xu hướng gdp 5 năm",
            "xu huong gdp 5 nam",
        ),
    ),
    "GDP_pc_growth_gap": IndicatorMeta(
        code="GDP_pc_growth_gap",
        name="GDP per Capita Growth Gap",
        category="growth_dynamics",
        unit="%",
        gold_table="gold_growth_dynamics",
        analytics_table="analytics_gold_growth_dynamics",
        description="Chênh lệch giữa tăng trưởng GDP tổng và GDP bình quân đầu người.",
        aliases=(
            "gdp per capita growth gap",
            "gdp pc growth gap",
            "chênh lệch gdp bình quân",
            "chenh lech gdp binh quan",
            "gdp bình quân đầu người",
            "gdp binh quan dau nguoi",
        ),
    ),
    "log_rGDP_pc_USD": IndicatorMeta(
        code="log_rGDP_pc_USD",
        name="Log Real GDP per Capita USD",
        category="growth_dynamics",
        unit="log(USD)",
        gold_table="gold_growth_dynamics",
        analytics_table=None,
        description="Log GDP thực bình quân đầu người tính bằng USD.",
        aliases=(
            "log real gdp per capita",
            "log rgdp per capita",
            "log gdp bình quân",
            "log gdp binh quan",
        ),
    ),

    
    # 2. Structural composition
    
    "agri_va_share": IndicatorMeta(
        code="agri_va_share",
        name="Agriculture Value Added Share",
        category="structural_composition",
        unit="%",
        gold_table="gold_structural_composition",
        analytics_table="analytics_gold_structural_composition",
        description="Tỷ trọng giá trị gia tăng nông nghiệp trong GDP.",
        aliases=(
            "agriculture value added share",
            "agri va share",
            "tỷ trọng nông nghiệp",
            "ty trong nong nghiep",
            "nông nghiệp trong gdp",
            "nong nghiep trong gdp",
            "giá trị gia tăng nông nghiệp",
            "gia tri gia tang nong nghiep",
        ),
    ),
    "manuf_va_share": IndicatorMeta(
        code="manuf_va_share",
        name="Manufacturing Value Added Share",
        category="structural_composition",
        unit="%",
        gold_table="gold_structural_composition",
        analytics_table="analytics_gold_structural_composition",
        description="Tỷ trọng giá trị gia tăng công nghiệp chế biến trong GDP.",
        aliases=(
            "manufacturing value added share",
            "manufacturing share",
            "manuf va share",
            "tỷ trọng công nghiệp chế biến",
            "ty trong cong nghiep che bien",
            "công nghiệp chế biến",
            "cong nghiep che bien",
            "sản xuất chế biến",
            "san xuat che bien",
        ),
    ),
    "food_bev_share_manuf": IndicatorMeta(
        code="food_bev_share_manuf",
        name="Food and Beverage Share of Manufacturing",
        category="structural_composition",
        unit="%",
        gold_table="gold_structural_composition",
        analytics_table="analytics_gold_structural_composition",
        description="Tỷ trọng ngành thực phẩm đồ uống trong sản xuất chế biến.",
        aliases=(
            "food beverage share manufacturing",
            "food and beverage manufacturing",
            "thực phẩm đồ uống",
            "thuc pham do uong",
            "tỷ trọng thực phẩm đồ uống",
            "ty trong thuc pham do uong",
        ),
    ),
    "GFCF_to_GDP": IndicatorMeta(
        code="GFCF_to_GDP",
        name="Gross Fixed Capital Formation to GDP",
        category="structural_composition",
        unit="%",
        gold_table="gold_structural_composition",
        analytics_table="analytics_gold_structural_composition",
        description="Tỷ lệ đầu tư tài sản cố định trên GDP.",
        aliases=(
            "gross fixed capital formation",
            "gfcf to gdp",
            "đầu tư tài sản cố định",
            "dau tu tai san co dinh",
            "tỷ lệ đầu tư",
            "ty le dau tu",
            "cường độ đầu tư",
            "cuong do dau tu",
        ),
    ),
    "GNI_to_GDP": IndicatorMeta(
        code="GNI_to_GDP",
        name="Gross National Income to GDP",
        category="structural_composition",
        unit="ratio",
        gold_table="gold_structural_composition",
        analytics_table="analytics_gold_structural_composition",
        description="Tỷ lệ GNI trên GDP.",
        aliases=(
            "gni to gdp",
            "gross national income to gdp",
            "gni/gdp",
            "tỷ lệ gni",
            "ty le gni",
            "thu nhập quốc dân",
            "thu nhap quoc dan",
        ),
    ),
    "flag_score": IndicatorMeta(
        code="flag_score",
        name="Data Quality Flag",
        category="structural_composition",
        unit="0-3",
        gold_table="gold_structural_composition",
        analytics_table=None,
        description="Điểm chất lượng dữ liệu.",
        aliases=(
            "flag score",
            "data quality flag",
            "điểm chất lượng dữ liệu",
            "diem chat luong du lieu",
            "chất lượng dữ liệu",
            "chat luong du lieu",
        ),
    ),
    "decade": IndicatorMeta(
        code="decade",
        name="Decade",
        category="structural_composition",
        unit="year",
        gold_table="gold_structural_composition",
        analytics_table=None,
        description="Thập kỷ của quan sát.",
        aliases=(
            "decade",
            "thập kỷ",
            "thap ky",
        ),
    ),

    
    # 3. Fiscal monetary
    
    "govdebt_GDP": IndicatorMeta(
        code="govdebt_GDP",
        name="Government Debt to GDP",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table="analytics_gold_fiscal_monetary",
        description="Tỷ lệ nợ công trên GDP.",
        aliases=(
            "government debt to gdp",
            "government debt",
            "public debt",
            "gov debt",
            "govdebt",
            "nợ công",
            "no cong",
            "nợ chính phủ",
            "no chinh phu",
            "debt gdp",
        ),
    ),
    "debt_change_YoY": IndicatorMeta(
        code="debt_change_YoY",
        name="Debt Change Year-over-Year",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Biến động nợ công so với năm trước.",
        aliases=(
            "debt change yoy",
            "debt change",
            "biến động nợ công",
            "bien dong no cong",
            "thay đổi nợ công",
            "thay doi no cong",
        ),
    ),
    "govrev_GDP": IndicatorMeta(
        code="govrev_GDP",
        name="Government Revenue to GDP",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Tỷ lệ thu ngân sách trên GDP.",
        aliases=(
            "government revenue to gdp",
            "government revenue",
            "gov revenue",
            "thu ngân sách",
            "thu ngan sach",
            "thu chính phủ",
            "thu chinh phu",
        ),
    ),
    "govexp_GDP": IndicatorMeta(
        code="govexp_GDP",
        name="Government Expenditure to GDP",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Tỷ lệ chi ngân sách trên GDP.",
        aliases=(
            "government expenditure to gdp",
            "government expenditure",
            "gov expenditure",
            "chi ngân sách",
            "chi ngan sach",
            "chi chính phủ",
            "chi chinh phu",
        ),
    ),
    "fiscal_balance_GDP": IndicatorMeta(
        code="fiscal_balance_GDP",
        name="Fiscal Balance to GDP",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table="analytics_gold_fiscal_monetary",
        description="Cân đối ngân sách trên GDP.",
        aliases=(
            "fiscal balance to gdp",
            "fiscal balance",
            "budget balance",
            "cân đối ngân sách",
            "can doi ngan sach",
            "thâm hụt ngân sách",
            "tham hut ngan sach",
            "bội chi ngân sách",
            "boi chi ngan sach",
        ),
    ),
    "cumulative_deficit_5yr": IndicatorMeta(
        code="cumulative_deficit_5yr",
        name="Cumulative Deficit 5-year",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Tổng thâm hụt tích lũy 5 năm.",
        aliases=(
            "cumulative deficit 5 year",
            "cumulative deficit",
            "thâm hụt tích lũy",
            "tham hut tich luy",
        ),
    ),
    "ltrate": IndicatorMeta(
        code="ltrate",
        name="Long-term Interest Rate",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Lãi suất dài hạn.",
        aliases=(
            "long term interest rate",
            "ltrate",
            "lãi suất dài hạn",
            "lai suat dai han",
            "trái phiếu chính phủ 10 năm",
            "trai phieu chinh phu 10 nam",
        ),
    ),
    "infl": IndicatorMeta(
        code="infl",
        name="Inflation GDP Deflator",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Lạm phát theo GDP deflator.",
        aliases=(
            "inflation deflator",
            "gdp deflator inflation",
            "infl",
            "lạm phát deflator",
            "lam phat deflator",
            "lạm phát theo deflator",
            "lam phat theo deflator",
        ),
    ),
    "real_interest_rate": IndicatorMeta(
        code="real_interest_rate",
        name="Real Interest Rate",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table="analytics_gold_fiscal_monetary",
        description="Lãi suất thực.",
        aliases=(
            "real interest rate",
            "lãi suất thực",
            "lai suat thuc",
            "real rate",
        ),
    ),
    "tax_revenue_pct_GDP": IndicatorMeta(
        code="tax_revenue_pct_GDP",
        name="Tax Revenue to GDP",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table="analytics_gold_fiscal_monetary",
        description="Tỷ lệ thu thuế trên GDP.",
        aliases=(
            "tax revenue to gdp",
            "tax revenue",
            "thu thuế",
            "thu thue",
            "tỷ lệ thu thuế",
            "ty le thu thue",
        ),
    ),
    "inflation_cpi": IndicatorMeta(
        code="inflation_cpi",
        name="Inflation CPI",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table="analytics_gold_fiscal_monetary",
        description="Lạm phát theo chỉ số giá tiêu dùng CPI.",
        aliases=(
            "inflation cpi",
            "cpi inflation",
            "lạm phát cpi",
            "lam phat cpi",
            "chỉ số giá tiêu dùng",
            "chi so gia tieu dung",
        ),
    ),
    "inflation_deflator": IndicatorMeta(
        code="inflation_deflator",
        name="Inflation Deflator",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Lạm phát theo GDP deflator.",
        aliases=(
            "inflation deflator",
            "gdp deflator",
            "lạm phát deflator",
            "lam phat deflator",
        ),
    ),
    "inflation_gap": IndicatorMeta(
        code="inflation_gap",
        name="Inflation Gap CPI minus Deflator",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table="analytics_gold_fiscal_monetary",
        description="Chênh lệch lạm phát CPI và GDP deflator.",
        aliases=(
            "inflation gap",
            "cpi deflator gap",
            "chênh lệch lạm phát",
            "chenh lech lam phat",
            "khoảng cách lạm phát",
            "khoang cach lam phat",
        ),
    ),
    "rolling_3yr_avg_cpi": IndicatorMeta(
        code="rolling_3yr_avg_cpi",
        name="3-Year Average CPI Inflation",
        category="fiscal_monetary",
        unit="%",
        gold_table="gold_fiscal_monetary",
        analytics_table=None,
        description="Trung bình trượt 3 năm của lạm phát CPI.",
        aliases=(
            "3 year average cpi inflation",
            "rolling 3 year cpi",
            "trung bình cpi 3 năm",
            "trung binh cpi 3 nam",
        ),
    ),

    
    # 4. Crisis risk
    
    "SovDebtCrisis": IndicatorMeta(
        code="SovDebtCrisis",
        name="Sovereign Debt Crisis",
        category="crisis_risk",
        unit="0/1",
        gold_table="gold_crisis_risk",
        analytics_table=None,
        description="Biến nhị phân: có khủng hoảng nợ công hay không.",
        aliases=(
            "sovereign debt crisis",
            "khủng hoảng nợ công",
            "khung hoang no cong",
            "khủng hoảng nợ chính phủ",
            "khung hoang no chinh phu",
        ),
    ),
    "CurrencyCrisis": IndicatorMeta(
        code="CurrencyCrisis",
        name="Currency Crisis",
        category="crisis_risk",
        unit="0/1",
        gold_table="gold_crisis_risk",
        analytics_table=None,
        description="Biến nhị phân: có khủng hoảng tiền tệ hay không.",
        aliases=(
            "currency crisis",
            "khủng hoảng tiền tệ",
            "khung hoang tien te",
            "khủng hoảng tỷ giá",
            "khung hoang ty gia",
        ),
    ),
    "BankingCrisis": IndicatorMeta(
        code="BankingCrisis",
        name="Banking Crisis",
        category="crisis_risk",
        unit="0/1",
        gold_table="gold_crisis_risk",
        analytics_table=None,
        description="Biến nhị phân: có khủng hoảng ngân hàng hay không.",
        aliases=(
            "banking crisis",
            "khủng hoảng ngân hàng",
            "khung hoang ngan hang",
        ),
    ),
    "crisis_composite": IndicatorMeta(
        code="crisis_composite",
        name="Crisis Composite Index",
        category="crisis_risk",
        unit="0-3",
        gold_table="gold_crisis_risk",
        analytics_table=None,
        description="Tổng số loại khủng hoảng xảy ra trong năm.",
        aliases=(
            "crisis composite",
            "crisis composite index",
            "chỉ số khủng hoảng tổng hợp",
            "chi so khung hoang tong hop",
            "mức độ khủng hoảng",
            "muc do khung hoang",
        ),
    ),
    "crisis_any": IndicatorMeta(
        code="crisis_any",
        name="Any Crisis Occurred",
        category="crisis_risk",
        unit="0/1",
        gold_table="gold_crisis_risk",
        analytics_table=None,
        description="Biến nhị phân: có ít nhất một loại khủng hoảng.",
        aliases=(
            "any crisis",
            "crisis any",
            "có khủng hoảng",
            "co khung hoang",
            "khủng hoảng bất kỳ",
            "khung hoang bat ky",
        ),
    ),
    "REER_deviation": IndicatorMeta(
        code="REER_deviation",
        name="REER Deviation",
        category="crisis_risk",
        unit="%",
        gold_table="gold_crisis_risk",
        analytics_table="analytics_gold_crisis_risk",
        description="Độ lệch tỷ giá hiệu dụng thực so với trung bình 5 năm.",
        aliases=(
            "reer deviation",
            "real effective exchange rate deviation",
            "độ lệch reer",
            "do lech reer",
            "tỷ giá hiệu dụng thực",
            "ty gia hieu dung thuc",
            "mất cân bằng tỷ giá",
            "mat can bang ty gia",
        ),
    ),
    "spending_efficiency": IndicatorMeta(
        code="spending_efficiency",
        name="Spending Efficiency",
        category="crisis_risk",
        unit="ratio",
        gold_table="gold_crisis_risk",
        analytics_table="analytics_gold_crisis_risk",
        description="Hiệu quả chi tiêu công.",
        aliases=(
            "spending efficiency",
            "hiệu quả chi tiêu",
            "hieu qua chi tieu",
            "hiệu quả chi tiêu công",
            "hieu qua chi tieu cong",
        ),
    ),

    
    # 5. Social welfare
    
    "unemployment_total": IndicatorMeta(
        code="unemployment_total",
        name="Unemployment Rate Total",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table="analytics_gold_social_welfare",
        description="Tỷ lệ thất nghiệp toàn bộ lực lượng lao động.",
        aliases=(
            "unemployment rate",
            "total unemployment",
            "unemployment total",
            "thất nghiệp",
            "that nghiep",
            "tỷ lệ thất nghiệp",
            "ty le that nghiep",
        ),
    ),
    "unemployment_youth": IndicatorMeta(
        code="unemployment_youth",
        name="Youth Unemployment Rate",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tỷ lệ thất nghiệp thanh niên.",
        aliases=(
            "youth unemployment",
            "youth unemployment rate",
            "thất nghiệp thanh niên",
            "that nghiep thanh nien",
            "thất nghiệp trẻ",
            "that nghiep tre",
        ),
    ),
    "youth_unemployment_gap": IndicatorMeta(
        code="youth_unemployment_gap",
        name="Youth Unemployment Gap",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table="analytics_gold_social_welfare",
        description="Chênh lệch thất nghiệp thanh niên và thất nghiệp tổng thể.",
        aliases=(
            "youth unemployment gap",
            "chênh lệch thất nghiệp thanh niên",
            "chenh lech that nghiep thanh nien",
            "youth gap",
            "khoảng cách thất nghiệp thanh niên",
            "khoang cach that nghiep thanh nien",
        ),
    ),
    "youth_gap_ratio": IndicatorMeta(
        code="youth_gap_ratio",
        name="Youth Gap Ratio",
        category="social_welfare",
        unit="ratio",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tỷ lệ thất nghiệp thanh niên trên thất nghiệp tổng thể.",
        aliases=(
            "youth gap ratio",
            "tỷ lệ thất nghiệp thanh niên trên tổng thể",
            "ty le that nghiep thanh nien tren tong the",
        ),
    ),
    "self_employed_pct": IndicatorMeta(
        code="self_employed_pct",
        name="Self-Employed Percentage",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tỷ lệ lao động tự doanh.",
        aliases=(
            "self employed",
            "self employed percentage",
            "lao động tự doanh",
            "lao dong tu doanh",
            "tự doanh",
            "tu doanh",
            "khu vực phi chính thức",
            "khu vuc phi chinh thuc",
        ),
    ),
    "poverty_headcount": IndicatorMeta(
        code="poverty_headcount",
        name="Poverty Headcount Ratio",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table="analytics_gold_social_welfare",
        description="Tỷ lệ dân số sống dưới ngưỡng nghèo.",
        aliases=(
            "poverty headcount",
            "poverty rate",
            "poverty ratio",
            "tỷ lệ nghèo",
            "ty le ngheo",
            "nghèo đói",
            "ngheo doi",
            "dân số nghèo",
            "dan so ngheo",
        ),
    ),
    "poverty_change_5yr": IndicatorMeta(
        code="poverty_change_5yr",
        name="Poverty Change 5-year",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table="analytics_gold_social_welfare",
        description="Biến động tỷ lệ nghèo trong 5 năm.",
        aliases=(
            "poverty change 5 year",
            "poverty change",
            "biến động nghèo",
            "bien dong ngheo",
            "thay đổi tỷ lệ nghèo",
            "thay doi ty le ngheo",
        ),
    ),
    "urban_pop_pct": IndicatorMeta(
        code="urban_pop_pct",
        name="Urban Population Percentage",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tỷ lệ dân số sống ở đô thị.",
        aliases=(
            "urban population percentage",
            "urban population",
            "tỷ lệ dân số đô thị",
            "ty le dan so do thi",
            "dân số đô thị",
            "dan so do thi",
            "đô thị hóa",
            "do thi hoa",
        ),
    ),
    "urban_pop_growth": IndicatorMeta(
        code="urban_pop_growth",
        name="Urban Population Growth",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tốc độ tăng dân số đô thị.",
        aliases=(
            "urban population growth",
            "urban growth",
            "tăng dân số đô thị",
            "tang dan so do thi",
            "tốc độ đô thị hóa",
            "toc do do thi hoa",
        ),
    ),
    "pop_density": IndicatorMeta(
        code="pop_density",
        name="Population Density",
        category="social_welfare",
        unit="people/km²",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Mật độ dân số.",
        aliases=(
            "population density",
            "mật độ dân số",
            "mat do dan so",
        ),
    ),
    "log_pop_density": IndicatorMeta(
        code="log_pop_density",
        name="Log Population Density",
        category="social_welfare",
        unit="log(people/km²)",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Logarit mật độ dân số.",
        aliases=(
            "log population density",
            "log mật độ dân số",
            "log mat do dan so",
        ),
    ),
    "pop_growth": IndicatorMeta(
        code="pop_growth",
        name="Population Growth",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tốc độ tăng dân số.",
        aliases=(
            "population growth",
            "tăng dân số",
            "tang dan so",
            "tốc độ tăng dân số",
            "toc do tang dan so",
        ),
    ),
    "hcons_share": IndicatorMeta(
        code="hcons_share",
        name="Household Consumption Share",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tỷ lệ tiêu dùng hộ gia đình trên GDP.",
        aliases=(
            "household consumption share",
            "household consumption",
            "tiêu dùng hộ gia đình",
            "tieu dung ho gia dinh",
            "tỷ lệ tiêu dùng hộ gia đình",
            "ty le tieu dung ho gia dinh",
        ),
    ),
    "hcons_growth": IndicatorMeta(
        code="hcons_growth",
        name="Household Consumption Growth",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table="analytics_gold_social_welfare",
        description="Tăng trưởng tiêu dùng hộ gia đình.",
        aliases=(
            "household consumption growth",
            "hcons growth",
            "tăng trưởng tiêu dùng hộ gia đình",
            "tang truong tieu dung ho gia dinh",
        ),
    ),
    "trade_pct_gdp": IndicatorMeta(
        code="trade_pct_gdp",
        name="Trade Percentage of GDP",
        category="social_welfare",
        unit="%",
        gold_table="gold_social_welfare",
        analytics_table=None,
        description="Tổng kim ngạch xuất nhập khẩu trên GDP.",
        aliases=(
            "trade percent gdp",
            "trade to gdp",
            "trade percentage of gdp",
            "thương mại trên gdp",
            "thuong mai tren gdp",
            "độ mở kinh tế",
            "do mo kinh te",
            "xuất nhập khẩu trên gdp",
            "xuat nhap khau tren gdp",
        ),
    ),
}


def get_indicator(code: str) -> IndicatorMeta | None:
    return INDICATORS.get(code)


def list_indicators() -> list[IndicatorMeta]:
    return list(INDICATORS.values())


def list_indicator_codes() -> list[str]:
    return list(INDICATORS.keys())